### ISSUE TITLE
[0.13] Worldgen crash

### ISSUE THREAD

**Issue by Lorelando** [PersonTheCat/CaveGenerator#17] opened 2019-03-06 12:25 UTC
This might be the same as #14.

Forge: 14.23.5.2814
Game crashed while exploring the world.

The gist contains the crash report and both activated and slightly modified presets: https://gist.github.com/Lorelando/c4119fb09e1f5c73c7e523fc94767a26

If you need me to try and reproduce the crash in a clean environment (as in without about 100 other mods) I'd be quite willing to try and reproduce it.

**Comment by PersonTheCat** [comment] 2019-03-06 12:34
Hey, thank you so much for pointing this out! I was actually just discussing a very similar bug with another user on Discord last night. I was never able to reproduce the issue, but I believe we were able to work it out. The crash was occurring whenever the terrain height was lower than `largeStalactites.minHeight`. This build includes a patch for that. Please try it out and let me know if the issue is fixed for you.


[CaveGenerator-0.14.zip](https://github.com/PersonTheCat/CaveGenerator/files/2936241/CaveGenerator-0.14.zip)

**Comment by Lorelando** [comment] 2019-03-07 11:52
Your update seems to fix it, I have not encountered another crash yet.

**Comment by PersonTheCat** [comment] 2019-03-07 12:27
Thanks for the confirmation! I'm working on some new features at the moment and then I'll release this on CurseForge in a couple of days or so.

**Comment by Lorelando** [comment] 2019-03-11 16:06
Looks like the nether doesn't like smaller numbers either :/
Game crashes upon entering the nether with decreased generation size and number of caves.
https://gist.github.com/Lorelando/58a581b8d6d6617e67aaa137b03e07ea

**Comment by Lorelando** [comment] 2019-03-11 17:29
Turns out the same crash occurs while using the default underground forest too.

**Comment by PersonTheCat** [comment] 2019-03-11 23:28
~~Huh. Neat. It's a bug with the heightmap not making a lot of sense in the Nether. I figured `World#getSeaLevel` would adjust to 32, but maybe not. I just need to think of a clean way for users to control the waterless heightmap settings. In the meantime, I can stop the crash by letting it treat the positions as invalid spawn points and making presets default to the overworld only. 
This might require a few design choices to be made...~~

Edit: I might have read a little too far into that. It seems like this is actually just the same issue as the first one, but I didn't fix it in both places. It's just the found height going below the min height.

**Comment by PersonTheCat** [comment] 2019-03-14 02:06
I believe this issue has been fixed in 0.14. Let me know if you're still able to reproduce it or if anything else comes up. Thanks for your help!

**Closed as completed by PersonTheCat** 2019-03-14 02:06 UTC
Labels: bug

**Comment by Lorelando** [comment] 2019-03-14 10:04
Yep, seems to fix it, many thanks :)
