### ISSUE TITLE
NullPointerException crash / compatibility with Worley's Caves

### ISSUE THREAD

**Issue by superfluke** [PersonTheCat/CaveGenerator#9] opened 2018-08-06 20:18 UTC
Heya, I'm one of the devs of Worley's Caves. We have a config option that allows for black listing our cave gen from specific dims, so players can have different cave generations in different dimensions. This works as expected when Worley's Caves is black listed from dim 0, with your caves in the overworld and Worley caves in the mining dim. However, trying to reverse things causes your mod to crash. It seems like your ravine generator is tied to your caves being in the overworld. 

Crash log: https://paste.ubuntu.com/p/gGZMzM6ntY/
cavegenerator-0.5.jar
worleycaves-1.1.1

**Comment by PersonTheCat** [comment] 2018-08-07 02:05
Hey, thanks for pointing this out! This is actually happening when data is being accessed from a World object. The object itself is most likely null when it tries to generate a ravine. I suspect that's because the mod is only being used to generate ravines and not just caves, and so the cave generator never has the chance to get setup. I never really intended for the mod to be used alongside other cave gen mods, but I can at least probably work around that. 

I'll set everything up and take a look at it to see what I can do and then let you know.

**Comment by superfluke** [comment] 2018-08-07 13:48
Yeah, I know it's a really unexpected edge case. Probably didn't plan for your caves to be overridden and the ravines still there. Just thought it'd be neat to see a pack with different types of caves in different dims, so thanks for checking it out.

**Comment by PersonTheCat** [comment] 2018-08-07 21:04
Okay, what I'm gonna do is have the mod store a reference to the previous MapGenBase object and call generate() on it if no CG presets are registered to the current dimension. I feel like that's a little sloppy, but it will sometimes work. The problem is that it can only work with one other MapGenBase at a time and of course, because only one newGen can be set at a time, I can only retrieve the last one that was available by the time by the time CG has access to InitMapGenEvent. But, if users are only using two cave gen mods at a time, or even more if they handle caves without using MapGenBase, it should work. Give me a bit to figure out the cleanest way to flesh that out. 

In the meantime, let me know if you have any other ideas or need anything else. Thanks again!

**Comment by PersonTheCat** [comment] 2018-08-09 02:04
Just tested this with the latest commit. I believe everything is working for me. I'm now able to get Worley's Caves generating in the overworld and CG caves in other dimensions. I'll most likely upload this to CurseForge tomorrow.

**Comment by PersonTheCat** [comment] 2018-08-16 05:45
I may go ahead and close this. Thanks for your help and please let me know if you run into any other issues.

**Closed as completed by PersonTheCat** 2018-08-16 05:45 UTC
