### ISSUE TITLE
Default preset generates "lava caves" in the nether - Correct Repo Edition

### ISSUE THREAD

**Issue by Quartofel** [PersonTheCat/CaveGenerator#46] opened 2022-01-02 16:56 UTC
Like the title says: default preset that comes with the mod generates weird "lava caves" in nether's lava lakes. I believe this is not intended:
![2022-01-02_17 45 47](https://user-images.githubusercontent.com/24753841/147883105-c0b40692-3594-4191-b6f8-1a45adceb515.png)
![2022-01-02_17 48 35](https://user-images.githubusercontent.com/24753841/147883112-020c6f73-4012-4bc8-9e57-83538f765241.png)

Issue encountered on Forge 36.2.20 (Minecraft 1.16.5), version 1.2 of the Cave Generator. I don't know if it is relevant, but CatLib version I'm running is 1.7.

**Comment by PersonTheCat** [comment] 2022-01-02 17:01
Oh cool, thanks for the details. I'm finishing up the port to 1.16 this week and will fix it then. Basically, the issue is even bigger than it looks here. Essentially, Cave Generator completely ignores which dimension it's generating in. I'm still working out how to get that info into the generators.

**Comment by PersonTheCat** [comment] 2022-11-07 15:49
This was a long time ago and I forgot to mention that it should have been fixed via CatLib. Marking this issue as resolved, but feel free to reopen it, if needed.

**Closed as completed by PersonTheCat** 2022-11-07 15:49 UTC
