### ISSUE TITLE
Crash on world start

### ISSUE THREAD

**Issue by Efimero** [PersonTheCat/CaveGenerator#1] opened 2018-07-24 21:29 UTC
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ReBindCorePlugin (Rebind.jar)
  SHLoadingPlugin (ScalingHealth.jar)
  BetterFoliageLoader (BetterFoliage.jar)
  SmoothWaterCore (SmoothWater.jar)
  F5FixLoadingPlugin (F5Fix.jar)
  LoadingPlugin (Quark.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  BetterAutoJumpCore (BetterAutoJump.jar)
  EcomodLoadingPlugin (EcologyMod.jar)
  ComfortsCoreLoadingPlugin (Comforts.jar)
  SSLoadingPlugin (SereneSeasons.jar)
  DynamicSurroundingsCore (DynamicSurroundings.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  CTMCorePlugin (CTM.jar)
  AstralCore (AstralSorcery.jar)
  LoadingPlugin (HardcoreDarkness.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 7/24/18 11:27 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at com.personthecat.cavegenerator.world.CaveGenerator.isTopBlock(CaveGenerator.java:726)
	at com.personthecat.cavegenerator.world.CaveGenerator.replaceSection(CaveGenerator.java:697)
	at com.personthecat.cavegenerator.world.CaveGenerator.addTunnel(CaveGenerator.java:346)
	at com.personthecat.cavegenerator.world.CaveManager.runGenerator(CaveManager.java:166)
	at com.personthecat.cavegenerator.world.CaveManager.func_180701_a(CaveManager.java:142)
	at com.personthecat.cavegenerator.world.CaveManager.func_186125_a(CaveManager.java:99)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:211)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.personthecat.cavegenerator.world.CaveGenerator.isTopBlock(CaveGenerator.java:726)
	at com.personthecat.cavegenerator.world.CaveGenerator.replaceSection(CaveGenerator.java:697)
	at com.personthecat.cavegenerator.world.CaveGenerator.addTunnel(CaveGenerator.java:346)
	at com.personthecat.cavegenerator.world.CaveManager.runGenerator(CaveManager.java:166)
	at com.personthecat.cavegenerator.world.CaveManager.func_180701_a(CaveManager.java:142)
	at com.personthecat.cavegenerator.world.CaveManager.func_186125_a(CaveManager.java:99)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:211)

-- Chunk to be generated --
Details:
	Location: -6,20
	Position hash: 90194313210
	Generator: net.minecraft.world.gen.ChunkGeneratorOverworld@6f3db742
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.16.0-2-amd64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2563904592 bytes (2445 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 10 total; -XX:+UseG1GC -Xmx5G -Xms5G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+AggressiveOpts -XX:+UseCompressedOops
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 140 mods loaded, 140 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                   | Version                   | Source                        | Signature                                |
	|:------- |:-------------------- |:------------------------- |:----------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft            | 1.12.2                    | minecraft.jar                 | None                                     |
	| UCHIJAA | mcp                  | 9.42                      | minecraft.jar                 | None                                     |
	| UCHIJAA | FML                  | 8.0.99.99                 | forge-1.12.2-14.23.4.2739.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                | 14.23.4.2739              | forge-1.12.2-14.23.4.2739.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | passableleavescore   | 1.0.0                     | minecraft.jar                 | None                                     |
	| UCHIJAA | charcoal_pit         | 1.16                      | CharcoalPit.jar               | None                                     |
	| UCHIJAA | embers               | 0.230                     | Embers.jar                    | None                                     |
	| UCHIJAA | aetherworks          | 1.12.2-1.0.0.3            | AetherWorks.jar               | None                                     |
	| UCHIJAA | crafttweaker         | 4.1.9                     | CT.jar                        | None                                     |
	| UCHIJAA | mtlib                | 3.0.5                     | MTLib.jar                     | None                                     |
	| UCHIJAA | modtweaker           | 4.0.13                    | MT.jar                        | None                                     |
	| UCHIJAA | jei                  | 4.11.0.204                | JEI.jar                       | None                                     |
	| UCHIJAA | abyssalcraft         | 1.9.4.10                  | AbyssalCraft.jar              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAA | acintegration        | 1.6.5                     | AbyssalCraftIntegrations.jar  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAA | antiqueatlas         | 4.4.9                     | AntiqueAtlas.jar              | None                                     |
	| UCHIJAA | antiqueatlasoverlay  | 1.2                       | AntiqueAtlas.jar              | None                                     |
	| UCHIJAA | examplemod           | 1.0                       | AntiqueAtlas.jar              | None                                     |
	| UCHIJAA | appleskin            | 1.0.9                     | AppleSkin.jar                 | None                                     |
	| UCHIJAA | athenaeum            | 1.12.2-1.14.0             | Athenaeum.jar                 | None                                     |
	| UCHIJAA | mousetweaks          | 2.8                       | MouseTweaks.jar               | None                                     |
	| UCHIJAA | artisanworktables    | 1.12.2-1.18.5-55-g5e08a2d | ArtisanWorktables.jar         | None                                     |
	| UCHIJAA | baubles              | 1.5.2                     | Baubles.jar                   | None                                     |
	| UCHIJAA | astralsorcery        | 1.9.3                     | AstralSorcery.jar             | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAA | wumpleutil           | 2.5.0                     | Wumple.jar                    | None                                     |
	| UCHIJAA | foodfunk             | 4.0.3                     | FoodFunk.jar                  | None                                     |
	| UCHIJAA | quark                | r1.4-125                  | Quark.jar                     | None                                     |
	| UCHIJAA | autoreglib           | 1.3-18                    | AutoRegLib.jar                | None                                     |
	| UCHIJAA | base                 | 3.9.0                     | Base.jar                      | None                                     |
	| UCHIJAA | bedrockreplacer      | 7.0.2                     | BedrockReplacer.jar           | None                                     |
	| UCHIJAA | betterautojump       | 1.1.1-mc1.12.2            | BetterAutoJump.jar            | None                                     |
	| UCHIJAA | betterfoliage        | 2.1.10                    | BetterFoliage.jar             | None                                     |
	| UCHIJAA | bonfires             | 1.2.2                     | Bonfires.jar                  | None                                     |
	| UCHIJAA | bottledmilk          | 1.0.0                     | BottledMilk.jar               | None                                     |
	| UCHIJAA | btg                  | 1.0.1                     | ByTheGods.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAA | camera               | 1.0.1                     | Camera.jar                    | None                                     |
	| UCHIJAA | catwalks             | 1.12.2-4.0.43             | Catwalks.jar                  | None                                     |
	| UCHIJAA | cavegenerator        | 0.2                       | CaveGenerator.jar             | None                                     |
	| UCHIJAA | ceramics             | 1.12-1.3.4                | Ceramics.jar                  | None                                     |
	| UCHIJAA | chameleon            | 1.12-4.1.3                | Chameleon.jar                 | None                                     |
	| UCHIJAA | chattweaks           | 5.1.11                    | ChatTweaks.jar                | None                                     |
	| UCHIJAA | ctm                  | MC1.12.2-0.3.2.18         | CTM.jar                       | None                                     |
	| UCHIJAA | chisel               | MC1.12.2-0.2.0.31         | Chisel.jar                    | None                                     |
	| UCHIJAA | chiselsandbits       | 14.20                     | ChiselBits.jar                | None                                     |
	| UCHIJAA | codechickenlib       | 3.2.0.345                 | CodeChicken.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | redstoneflux         | 2.0.2                     | RedstoneFlux.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | cofhcore             | 4.5.3                     | COFHCore.jar                  | None                                     |
	| UCHIJAA | cofhworld            | 1.2.0                     | COFHWorld.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | comforts             | 1.2.0                     | Comforts.jar                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAA | coralreef            | 2.0                       | CoralReef.jar                 | None                                     |
	| UCHIJAA | wearablebackpacks    | 3.1.3                     | WearableBackpacks.jar         | None                                     |
	| UCHIJAA | corpsecomplex        | 1.0.2.2                   | CorpseComplex.jar             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAA | contenttweaker       | 1.12.2-4.6.0              | CoT.jar                       | None                                     |
	| UCHIJAA | ctgui                | 1.0.0                     | CT.jar                        | None                                     |
	| UCHIJAA | crafttweakerjei      | 2.0.2                     | CT.jar                        | None                                     |
	| UCHIJAA | culinaryconstruct    | 1.1.0                     | CulinaryConstruct.jar         | None                                     |
	| UCHIJAA | diethopper           | 1.1                       | DietHopper.jar                | None                                     |
	| UCHIJAA | drawbridges          | 0.1                       | Drawbridges.jar               | None                                     |
	| UCHIJAA | dsurround            | 3.4.9.14                  | DynamicSurroundings.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAA | presets              | 3.4.9.14                  | DynamicSurroundings.jar       | None                                     |
	| UCHIJAA | ecomod               | 1.12.2-1.5.0.0            | EcologyMod.jar                | None                                     |
	| UCHIJAA | endreborn            | 0.1.9                     | EndReborn.jar                 | None                                     |
	| UCHIJAA | theoneprobe          | 1.4.23                    | TheOneProbe.jar               | None                                     |
	| UCHIJAA | thermalfoundation    | 2.5.0                     | ThermalFoundation.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | immersiveengineering | 0.12-84                   | ImmersiveEngineering.jar      | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAA | engineersdoors       | 0.6.0                     | EngineersDoors.jar            | None                                     |
	| UCHIJAA | enhancedvisuals      | 1.0                       | EnhancedVisuals.jar           | None                                     |
	| UCHIJAA | evilnotchlib         | 1.2.3-SNAPSHOT-30         | EvilNotch.jar                 | None                                     |
	| UCHIJAA | thermalexpansion     | 5.5.0                     | ThermalExpansion.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | exchangers           | 1.12.2-2.7.2              | Exchangers.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJAA | minegems             | 1.2.4                     | ExtraGems.jar                 | None                                     |
	| UCHIJAA | ferdinandsflowers    | 1.10.1b                   | Ferdinand.jar                 | None                                     |
	| UCHIJAA | placebo              | 1.4.0                     | Placebo.jar                   | None                                     |
	| UCHIJAA | foundry              | 3.1.4.1                   | Foundry.jar                   | None                                     |
	| UCHIJAA | gardenstuff          | 1.12-2.1.1                | GardenStuff.jar               | None                                     |
	| UCHIJAA | geographicraft       | 0.8.7                     | GeographyCraft.jar            | None                                     |
	| UCHIJAA | geolosys             | 2.0.0                     | Geolosys.jar                  | None                                     |
	| UCHIJAA | grue                 | 1.3.5                     | Grue.jar                      | None                                     |
	| UCHIJAA | hardcoredarkness     | 2.0                       | HardcoreDarkness.jar          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAA | heartdrops           | 1.12.2-2.0.8.1            | HeartDrops.jar                | None                                     |
	| UCHIJAA | hgp                  | Release                   | HorizontalGlassPane.jar       | None                                     |
	| UCHIJAA | immersivepetroleum   | 1.1.9                     | ImmersivePetroleum.jar        | None                                     |
	| UCHIJAA | incontrol            | 0.1.0                     | InControl.jar                 | None                                     |
	| UCHIJAA | initialinventory     | 2.0.2                     | InitialInventory.jar          | None                                     |
	| UCHIJAA | justenoughdimensions | 1.6.0-dev.20180619.124018 | JED.jar                       | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAA | harvestcraft         | 1.12.2u                   | PamsHarvestcraft.jar          | None                                     |
	| UCHIJAA | jehc                 | 1.12.2                    | JEHC.jar                      | None                                     |
	| UCHIJAA | justenoughpetroleum  | 0.1                       | JEP.jar                       | None                                     |
	| UCHIJAA | jeresources          | 0.8.8.47                  | JER.jar                       | None                                     |
	| UCHIJAA | testdummy            | 1.12                      | Mmm.jar                       | None                                     |
	| UCHIJAA | mob_mash             | 2.4                       | MobMash.jar                   | None                                     |
	| UCHIJAA | morecauldrons        | 1.4.2                     | MoreCauldrons.jar             | None                                     |
	| UCHIJAA | mystcraft            | 0.13.6.00                 | Mystcraft.jar                 | None                                     |
	| UCHIJAA | naturalnetherportals | 1.2.0                     | NaturalNetherPortals.jar      | None                                     |
	| UCHIJAA | nex                  | 2.1.14.15                 | NetherEx.jar                  | None                                     |
	| UCHIJAA | nonvflash            | 1.2.0                     | NoNVFlash.jar                 | None                                     |
	| UCHIJAA | norecipebook         | 1.2.1                     | NoRecipeBook.jar              | None                                     |
	| UCHIJAA | norespawnscreen      | 1.2.2                     | NoRespawnScreen.jar           | None                                     |
	| UCHIJAA | oversaturation       | 1.0                       | Oversaturation.jar            | None                                     |
	| UCHIJAA | bonecraft            | 1.12.2a                   | PamsBonecraft.jar             | None                                     |
	| UCHIJAA | ping                 | 1.4.3                     | Ping.jar                      | None                                     |
	| UCHIJAA | plants2              | 2.9.2                     | Plants.jar                    | None                                     |
	| UCHIJAA | playerweight         | 1.4                       | PlayerWeight.jar              | None                                     |
	| UCHIJAA | primalchests         | 1.0.3                     | PrimalChests.jar              | None                                     |
	| UCHIJAA | rustic               | 1.0.6                     | Rustic.jar                    | None                                     |
	| UCHIJAA | primal               | 0.6.66                    | PrimalCore.jar                | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAA | pyramidplunder       | 1.12.2-1.0                | PyramidPlunder.jar            | None                                     |
	| UCHIJAA | quickleafdecay       | 1.2.4                     | QuickLeafDecay.jar            | None                                     |
	| UCHIJAA | rebind               | 2.7.0                     | Rebind.jar                    | None                                     |
	| UCHIJAA | rootsclassic         | 1.12.2-1.0.3              | Roots1.jar                    | None                                     |
	| UCHIJAA | roots                | 0.104                     | Roots2.jar                    | None                                     |
	| UCHIJAA | silentlib            | 2.3.2                     | SilentLib.jar                 | None                                     |
	| UCHIJAA | scalinghealth        | 1.3.19                    | ScalingHealth.jar             | None                                     |
	| UCHIJAA | scannable            | 1.6.3.19                  | Scannable.jar                 | None                                     |
	| UCHIJAA | sereneseasons        | 1.2.3                     | SereneSeasons.jar             | None                                     |
	| UCHIJAA | simpledivegear       | 1.0.3                     | SimpleDivingGear.jar          | None                                     |
	| UCHIJAA | smoothwater          | 0.1.3                     | SmoothWater.jar               | None                                     |
	| UCHIJAA | snowaccumulation     | 1.0.0                     | SnowAccumulation.jar          | None                                     |
	| UCHIJAA | soot                 | 0.18hotfix                | Soot.jar                      | None                                     |
	| UCHIJAA | soundfilters         | 0.10_for_1.12             | SoundFilters.jar              | None                                     |
	| UCHIJAA | spartanshields       | 1.4.1                     | SpartanShields.jar            | None                                     |
	| UCHIJAA | spartanweaponry      | beta 1.1.2                | SpartanWeaponry.jar           | None                                     |
	| UCHIJAA | steamworld           | 0.3.1.3a                  | SteamWorld.jar                | None                                     |
	| UCHIJAA | stg                  | 1.12.2-1.2.3              | SwingThroughGrass.jar         | None                                     |
	| UCHIJAA | beneath              | 1.4.2                     | TheBeneath.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAA | thermalcultivation   | 0.3.0                     | ThermalCultivation.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | thermalinnovation    | 0.3.0                     | ThermalInnovation.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAA | toastcontrol         | 1.7.0                     | ToastControl.jar              | None                                     |
	| UCHIJAA | toolprogression      | 1.12.2-1.5.4              | ToolProgression.jar           | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| UCHIJAA | treechopper          | 1.2.4                     | TreeChopper.jar               | None                                     |
	| UCHIJAA | treetweaker          | 1.1                       | TreeTweaker.jar               | None                                     |
	| UCHIJAA | twilightforest       | 3.7.424                   | TwilightForest.jar            | None                                     |
	| UCHIJAA | twitchintegration    | 4.1.5                     | TwitchIntegration.jar         | None                                     |
	| UCHIJAA | underphangables      | 1.0.0                     | UnderpHangables.jar           | None                                     |
	| UCHIJAA | subterranaenwaters   | 1.12.2-1.5.6              | UnderwaterCaves.jar           | None                                     |
	| UCHIJAA | unloader             | 1.2.0                     | Unloader.jar                  | None                                     |
	| UCHIJAA | webslinger           | 2.0.0                     | WebSlinger.jar                | None                                     |
	| UCHIJAA | weeping-angels       | 17                        | WeepingAngels.jar             | None                                     |
	| UCHIJAA | ebwizardry           | 4.1.2                     | Wizardry.jar                  | None                                     |
	| UCHIJAA | xtones               | 1.12-1.0.8-11             | Xtones.jar                    | None                                     |
	| UCHIJAA | passableleaves       | 2.0.0                     | PassableLeaves.jar            | None                                     |

	Loaded coremods (and transformers): 
ReBindCorePlugin (Rebind.jar)
  ru.austeretony.rebind.coremod.ReBindClassTransformer
SHLoadingPlugin (ScalingHealth.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
BetterFoliageLoader (BetterFoliage.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
SmoothWaterCore (SmoothWater.jar)
  pl.asie.smoothwater.SmoothWaterTransformer
F5FixLoadingPlugin (F5Fix.jar)
  de.morrien.f5fix.F5FixTransformer
LoadingPlugin (Quark.jar)
  vazkii.quark.base.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
BetterAutoJumpCore (BetterAutoJump.jar)
  com.mmyzd.betterautojump.asm.ClassTransformer
EcomodLoadingPlugin (EcologyMod.jar)
  ecomod.asm.EcomodClassTransformer
ComfortsCoreLoadingPlugin (Comforts.jar)
  c4.comforts.asm.SleepTransformer
SSLoadingPlugin (SereneSeasons.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings.jar)
  org.blockartistry.DynSurround.asm.Transformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
CTMCorePlugin (CTM.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AstralCore (AstralSorcery.jar)
  
LoadingPlugin (HardcoreDarkness.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 
	0: Working: false |Last Profiler section: [UNKNOWN]| Interrupted:false

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by PersonTheCat** [comment] 2018-07-24 22:13
That's odd. I definitely can't reproduce this. The same line also exists in Forge by default, so I'm not sure how it would cause any issues. :/ Are you using a preset, by chance? If so, do you mind sharing it with me?

Thanks!

**Comment by Efimero** [comment] 2018-07-24 22:28
no, just standard creative world, but maybe Geographicraft is messing with it?
I think that's the only one that would change worldgen
Quark and UnderwaterCaves also change caves, but I think they do it after generation
I have no issues if I remove this mod, everything works normally except CaveGeneration

this shouldn't matter, but... seed: `9200743987257643984`

**Comment by Mattabase** [comment] 2018-07-25 02:20
Also happens to me. I have yet too test the mod by itself. 

http://bit.ly/2LMS4iv

**Comment by PersonTheCat** [comment] 2018-07-25 03:56
Thanks for the help. Having received a few different reports of the same issue, it's pretty clear that this issue occurs whenever any given mod has registered its own BiomeProvider, and so the mod isn't able to correctly retrieve the current biome. Basically, the issue is just the result of the fact that multiple mods are trying to do the same thing at the same time. I suspect there is no way to actually correct this issue, but I can at least stop it from crashing. The only side effect will be that caves might protrude through surfaces more so than they should. In the following updates before the first "release" version of the mod, I will investigate this issue again to reconsider how I might approach the situation. It's suspicious to me that Forge is able to use this same method, but yet somehow Cave Generator is not. 

Regardless... If either of you wouldn't mind, please try this development build and confirm whether it's working with all of the other mods you have installed. Make sure to extract it first and then let me know if you encounter the same or especially a different crash. I would appreciate it!

[cavegenerator-0.3.zip](https://github.com/PersonTheCat/CaveGenerator/files/2226409/cavegenerator-0.3.zip)

Edit: There may actually be a few other issues when using these mods. I am aware of a second crash that occurs when using the new noise-based cave generator and one of these mods. I'm going to take a little bit more time to investigate everything thoroughly.

Edit 2: Just realized that the actual problem is not that the biome itself is invalid or not retrievable, it's actually that the World object which gets passed into Cave Generator's cave manager is null, meaning I can't retrieve any information from it. All of the above crashes were the result of that same problem, and which ones were manifested were just whichever ones occurred first. I fixed the issue by storing previously valid World objects and not ever replacing them with invalid ones. I need to do some more tests to make sure everything stays accurate, and then a new build will be pushed out afterward. I'll update when that happens.

**Comment by PersonTheCat** [comment] 2018-07-26 03:00
Okay. Everything is working exactly as it should for me. I still have not tested every single one of these mods on all of these lists, but seeing as the crash is basically the same in each case, I suspect the problem will be fixed for most of them. As always when combining multiple terrain gen mods, issues are easy to encounter. Please let me know of any more that you find and I'll look into them as soon as possible. 

Thanks again for your help!

**Comment by Efimero** [comment] 2018-07-26 12:05
aaa! it works! help! <3 <3 <3

**Closed as completed** 2018-07-26 12:26 UTC

**Comment by PersonTheCat** [comment] 2018-07-26 14:51
Great! Thanks for your help.
